steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_BACKEND_URL=${_NEXT_PUBLIC_BACKEND_URL}'
      - '-t'
      - 'asia-south1-docker.pkg.dev/chunav-sathi-494615/election-guide-repo/frontend:latest'
      - '.'
images:
  - 'asia-south1-docker.pkg.dev/chunav-sathi-494615/election-guide-repo/frontend:latest'
